import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({  }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets build a cool app</h1>
      <Link href="/aboutme">About me</Link>

      <p>My name is: {name}</p>
    </div>
  );
}





// export async function getServerSideProps(context) {
//   const name = await fetch("http://localhost:3000/api/man")
//     .then((res) => res.json())
//     .then((data) => data.name);

//   return {
//     props: {
//       name,
//     },
//   };
// }
